### ISSUE TITLE
ASCII codec can't decode byte - Unable to Generate Report 

### ISSUE THREAD

**Issue by qrodgers13** [thomfre/OSCP-Exam-Report-Template#3]
Attempting to generate the lab report based upon my exercises and getting the following error. Generating the exam-report seems to work as expected. 

Been going through my code from my BoF that I included wasn't sure if you had any other ideas. 
```
root@kali:~/Desktop/oscp/OSCP-Exam-Lab-Reports# ./generate-report.sh lab-report
[*] Preparing lab report for generation
[*] Stitching together targets, appendices and exercises
[*] Correcting relative image URLs
[*] Generating report
Traceback (most recent call last):
  File "/usr/local/bin/markdown-pp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/MarkdownPP/main.py", line 112, in main
    MarkdownPP.MarkdownPP(input=mdpp, output=md, modules=modules)
  File "/usr/local/lib/python2.7/dist-packages/MarkdownPP/MarkdownPP.py", line 28, in __init__
    pp.process()
  File "/usr/local/lib/python2.7/dist-packages/MarkdownPP/Processor.py", line 49, in process
    transforms = module.transform(self.data)
  File "/usr/local/lib/python2.7/dist-packages/MarkdownPP/Modules/Include.py", line 40, in transform
    includedata = self.include(match)
  File "/usr/local/lib/python2.7/dist-packages/MarkdownPP/Modules/Include.py", line 106, in include
    result += self.include_file(filename, pwd, shift)
  File "/usr/local/lib/python2.7/dist-packages/MarkdownPP/Modules/Include.py", line 74, in include_file
    data[linenum] = "#" + data[linenum]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 60: ordinal not in range(128)
```

**Comment by qrodgers13** [comment]
It appears the issue was the result of using `Markdown-PP` with python2 instead of python3. Uninstalled the python2 version and re-installed with pip3 and it works as expected.
